#!/bin/sh
# In conf, refresh the ./vcs clone to the latest main after a pull/merge.
# Guard: only run when this repo's Makefile defines vcs-fetch (i.e. we
# are in conf, not some other repo that inherited this hook).
if test -f Makefile && grep -q '^vcs-fetch:' Makefile; then
    make vcs-fetch
fi
